import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
test('real stdio MCP handshake, tools, resources, prompts and persistence',async t=>{
  const directory=await mkdtemp(path.join(os.tmpdir(),'drawio-mcp-'));
  const transport=new StdioClientTransport({command:process.execPath,args:[fileURLToPath(new URL('../src/server.js',import.meta.url))],env:{...process.env,DRAWIO_OUTPUT_DIR:directory},stderr:'pipe'});
  let stderr='';transport.stderr?.on('data',chunk=>{stderr+=chunk;});
  const client=new Client({name:'integration-test',version:'1.0.0'});
  t.after(async()=>{await client.close();await rm(directory,{recursive:true,force:true});});
  await client.connect(transport);
  const tools=await client.listTools();assert.equal(tools.tools.length,12);
  const call=async(name,args={})=>{const response=await client.callTool({name,arguments:args});assert.ok(!response.isError,JSON.stringify(response));return response.structuredContent??JSON.parse(response.content[0].text);};
  assert.equal((await call('list_diagram_templates')).templates.length,12);
  const template=await call('get_diagram_template',{name:'cloud'});
  const {xml}=await call('create_diagram',{graph:template.graph});
  assert.equal((await call('validate_diagram',{xml})).valid,true);
  await call('save_diagram',{filename:'cloud.drawio',xml});
  assert.equal((await call('read_diagram',{filename:'cloud.drawio'})).xml,xml);
  assert.deepEqual((await call('list_saved_diagrams')).files,['cloud.drawio']);
  const bad=await client.callTool({name:'create_diagram',arguments:{graph:{nodes:[{id:'a'}],edges:[{source:'a',target:'missing'}]}}});assert.equal(bad.isError,true);
  assert.equal((await call('validate_diagram',{xml:'<invalid/>'})).valid,false);
  const edited=await call('edit_diagram',{xml,operations:[{action:'update',id:'api',label:'New API'}]});
  assert.ok((await call('inspect_diagram',{xml:edited.xml})).pages[0].cells.some(c=>c.label==='New API'));
  assert.ok((await call('get_editor_url',{xml})).url.startsWith('https://app.diagrams.net/'));
  const combined=await call('combine_diagrams',{diagrams:[{xml},{xml}]});
  assert.equal((await call('inspect_diagram',{xml:combined.xml})).pages.length,2);
  assert.equal((await client.listResources()).resources.length,1);
  assert.match((await client.readResource({uri:'drawio://guide'})).contents[0].text,/editable/);
  assert.equal((await client.listPrompts()).prompts.length,1);
  assert.equal((await client.getPrompt({name:'design_diagram',arguments:{description:'A network'}})).messages.length,1);
  assert.equal(stderr,'');
});
